[package]
name = "GameJamFall2023"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.11.2"}
rand = "0.8.5"
bevy_rapier2d = { version = "0.22.0", features = ["simd-stable"] }
bevy_ecs_ldtk = "0.8.0"
bevy_ecs_tilemap = "0.11.0"
thiserror = "1.0.49"
